imports:
    - { resource: easy_admin/global.yml }
    - { resource: easy_admin/menu.yml }
    - { resource: easy_admin/article.yml }
    - { resource: easy_admin/page.yml }
    - { resource: easy_admin/image.yml }
    - { resource: easy_admin/comment.yml }
    - { resource: easy_admin/setting.yml }
    - { resource: easy_admin/user.yml }
    - { resource: easy_admin/theme.yml }
    - { resource: easy_admin/menuItem.yml }

